steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/ministry-data-cleaning'
      - '-f'
      - 'api/Dockerfile'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/ministry-data-cleaning'

images:
  - 'gcr.io/$PROJECT_ID/ministry-data-cleaning'

timeout: '600s'

